#Provided by @mrlesmithjr
#EveryThingShouldBeVirtual.com

Vagrant.configure(2) do |config|
  config.vm.box = "mrlesmithjr/ubuntu-14.04-base"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "graylog2-server"
    vb.memory = "2048"
    vb.cpus = "2"  
  end
  config.vm.define :server do |srv|
    srv.vm.name = "graylog2-server"
    srv.vm.hostname = "graylog2-server"
    srv.vm.network "forwarded_port", guest: 9000, host: 9000
    srv.vm.provision :shell, path: "provision.sh"
  end
end
